/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.Produccionn;

import java.awt.Frame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelo.Conexion;

/**
 *
 * @author EQUIPO
 */
public class DetalleProduccionProducto extends javax.swing.JDialog {

    private int idProduccion;

    public DetalleProduccionProducto(java.awt.Frame parent, boolean modal,
            int idProduccion, String nombre,
            String fechaInicio, String fechaFin,
            String estado) {
        super(parent, modal);
        this.idProduccion = idProduccion;
        initComponents();
        setLocationRelativeTo(parent);
        
        DetallePedido es = new DetallePedido(this.idProduccion);
        es.setSize(1090, 690);
        es.setLocation(0, 0);

        jPanel2.removeAll();
        jPanel2.add(es);
        jPanel2.revalidate();
        jPanel2.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnvolver = new RSMaterialComponent.RSButtonShape();
        btnEtapa = new RSMaterialComponent.RSButtonShape();
        btndetalle = new RSMaterialComponent.RSButtonShape();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnvolver.setBackground(new java.awt.Color(46, 49, 82));
        btnvolver.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volver (1).png"))); // NOI18N
        btnvolver.setText("Volver");
        btnvolver.setBackgroundHover(new java.awt.Color(67, 150, 209));
        btnvolver.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnvolver.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        btnEtapa.setBackground(new java.awt.Color(46, 49, 82));
        btnEtapa.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnEtapa.setText("Etapa de produccion");
        btnEtapa.setBackgroundHover(new java.awt.Color(67, 150, 209));
        btnEtapa.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnEtapa.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        btnEtapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtapaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEtapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 170, 40));

        btndetalle.setBackground(new java.awt.Color(46, 49, 82));
        btndetalle.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btndetalle.setText("    Detalle de pedido");
        btndetalle.setBackgroundHover(new java.awt.Color(67, 150, 209));
        btndetalle.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btndetalle.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        btndetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndetalleActionPerformed(evt);
            }
        });
        jPanel1.add(btndetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 170, 40));

        jPanel2.setBackground(new java.awt.Color(234, 234, 234));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 1150, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1211, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        this.dispose();

    }//GEN-LAST:event_btnvolverActionPerformed

    private void btnEtapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtapaActionPerformed
        ProduccionContEtapa es = new ProduccionContEtapa(this.idProduccion);
        es.setSize(1090, 690);
        es.setLocation(0, 0);

        jPanel2.removeAll();
        jPanel2.add(es);
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_btnEtapaActionPerformed

    private void btndetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetalleActionPerformed
        DetallePedido es = new DetallePedido(this.idProduccion);
        es.setSize(1090, 690);
        es.setLocation(0, 0);

        jPanel2.removeAll();
        jPanel2.add(es);
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_btndetalleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleProduccionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleProduccionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleProduccionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleProduccionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Proporciona valores por defecto para los parámetros faltantes
                DetalleProduccionProducto dialog = new DetalleProduccionProducto(
                        new javax.swing.JFrame(), // parent
                        true, // modal
                        0, // idProduccion (valor por defecto)
                        "Sin nombre", // nombre (valor por defecto)
                        "", // fechaInicio (valor por defecto)
                        "", // fechaFin (valor por defecto)
                        "Sin estado" // estado (valor por defecto)
                );

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonShape btnEtapa;
    private RSMaterialComponent.RSButtonShape btndetalle;
    private RSMaterialComponent.RSButtonShape btnvolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
