/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Produccionn;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import modelo.Conexion;

/**
 *
 * @author EQUIPO
 */
public class DetallePedido extends javax.swing.JPanel {

    private final int idProduccion;
public DetallePedido(int idProduccion) {
    this.idProduccion = idProduccion;
    initComponents();
    cargarDatosPedido(); // Método que carga los datos desde la BD
}
    /**
     * Creates new form DetallePedido
     */
    // Constructor corregido
    public DetallePedido(int idProduccion, String nombre, String fechaInicio, 
                    String fechaFin, String estado, String cantidad, String dimensiones) {
    System.out.println("ID recibido en constructor: " + idProduccion); // Debug
    this.idProduccion = idProduccion;
    initComponents();
    // Asignar valores directamente
    this.nombre.setText(nombre != null ? nombre : "");
    this.fecha_ini.setText(fechaInicio != null ? fechaInicio : "");
    this.fecha_fin.setText(fechaFin != null ? fechaFin : "");
    this.estado.setText(estado != null ? estado : "");
    this.cantidad.setText(cantidad != null ? cantidad : "0");
    this.dimensiones.setText(dimensiones != null ? dimensiones : "");
}

    private void cargarDatosPedido() {
        limpiarCampos(); // Limpia antes de cargar nuevos datos

        try (Connection con = new Conexion().getConnection()) {
            String sql = "SELECT p.fecha_inicio, p.fecha_fin, p.estado, "
                    + "dp.cantidad, dp.dimensiones, dp.descripcion "
                    + "FROM produccion p "
                    + "JOIN detalle_pedido dp ON p.detalle_pedido_iddetalle_pedido = dp.iddetalle_pedido "
                    + "JOIN pedido pe ON dp.pedido_id_pedido = pe.id_pedido "
                    + "WHERE p.id_produccion = ?";

            try (PreparedStatement ps = con.prepareStatement(sql)) {
                ps.setInt(1, idProduccion);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        // Formatear fechas si es necesario
                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

                        nombre.setText(rs.getString("descripcion") != null ? rs.getString("descripcion") : "No disponible");
                        fecha_ini.setText(rs.getDate("fecha_inicio") != null ? sdf.format(rs.getDate("fecha_inicio")) : "No definida");
                        fecha_fin.setText(rs.getDate("fecha_fin") != null ? sdf.format(rs.getDate("fecha_fin")) : "No definida");
                        estado.setText(rs.getString("estado") != null ? rs.getString("estado") : "Sin estado");
                        cantidad.setText(rs.getString("cantidad") != null ? rs.getString("cantidad") : "0");
                        cantidad1.setText(cantidad.getText()); // Usamos el mismo valor
                        dimensiones.setText(rs.getString("dimensiones") != null ? rs.getString("dimensiones") : "No especificadas");
                    } else {
                        // Si no hay datos, muestra un mensaje en un campo
                        nombre.setText("No se encontraron datos para el pedido ID: " + idProduccion);
                    }
                }
            }
        } catch (SQLException e) {
            nombre.setText("Error al cargar datos");
            JOptionPane.showMessageDialog(this,
                    "Error de conexión: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fecha_ini = new javax.swing.JLabel();
        fecha_fin = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        dimensiones = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cantidad1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(234, 234, 234));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        fecha_ini.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fecha_ini.setForeground(new java.awt.Color(0, 0, 0));
        fecha_ini.setText("fecha_ini");
        jPanel2.add(fecha_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        fecha_fin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fecha_fin.setForeground(new java.awt.Color(0, 0, 0));
        fecha_fin.setText("fecha_fin");
        jPanel2.add(fecha_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        cantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidad.setForeground(new java.awt.Color(0, 0, 0));
        cantidad.setText("cantidad");
        jPanel2.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        dimensiones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dimensiones.setForeground(new java.awt.Color(0, 0, 0));
        dimensiones.setText("dimensiones");
        jPanel2.add(dimensiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        estado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        estado.setForeground(new java.awt.Color(0, 0, 0));
        estado.setText("estado");
        jPanel2.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Estado actual:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Etapas terminadas:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 700, 2));

        nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 0));
        nombre.setText("Nombre");
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Fecha de fin:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Dimensiones:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cantidad:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Estado:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Cantidad:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        cantidad1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidad1.setForeground(new java.awt.Color(0, 0, 0));
        cantidad1.setText("cantidad");
        jPanel2.add(cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Fecha de inicio: ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCampos() {
        nombre.setText("");
        fecha_ini.setText("");
        fecha_fin.setText("");
        estado.setText("");
        cantidad.setText("");
        cantidad1.setText("");
        dimensiones.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantidad;
    private javax.swing.JLabel cantidad1;
    private javax.swing.JLabel dimensiones;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel fecha_fin;
    private javax.swing.JLabel fecha_ini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
